# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbe2b732070857cf8343890c0ba93956f2bb7c0798ef8728364fc405e219faf62f342e9ce315555718985d082734a41bf2b9c39cb8a7f0828bc2adc8d3c296da

test:
  secret_key_base: 9e9c4a7fdc5a3f9f13a5496bea937c8ef9ac04b4b565d02b3aa02ff8f5d5e8fadb912dc2ad37818249bda09cb0b043fc9f5ad2b177b87ca0aa0a78dc006d99eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
